config/routes.rb
Controlr::Application.routes.draw do

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :registration => 'register',
    :sign_up => 'signup'
  }

  resources :accounts

  resources :domains do
    collection do
      post 'switch'
    end
    member do
      get 'sync'
    end
  end
  resources :users

  resources :aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :mailboxes do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :default_name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :default_aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :roles do
    collection do
      get 'report'
      post 'report'
    end
  end

  root :to => 'accounts#show'

end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
  authorize_resource
  append_before_filter do
    redirect_to(domains_url, :alert => t('aliases.domain_missing')) unless @domain
  end

  rescue_from DataMapper::ObjectNotFoundError do |exception|
    redirect_to aliases_path, :alert => t('aliases.missing')
  end

  # GET /aliases
  # GET /aliases.xml
  def index
    @aliases = @domain.aliases.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @aliases }
    end
  end

  # GET /aliases/1
  # GET /aliases/1.xml
  def show
    redirect_to edit_alias_path(params[:id])
  end

  # GET /aliases/new
  # GET /aliases/new.xml
  def new
    @alias = @domain.aliases.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alias }
    end
  end

  # GET /aliases/1/edit
  def edit
    @alias = @domain.aliases.get!(params[:id])
  end

  # POST /aliases
  # POST /aliases.xml
  def create
    @alias = @domain.aliases.new(params[:alias])

    respond_to do |format|
      if @alias.save
        flash[:notice] = t('aliases.create.notice')
        format.html { redirect_to(aliases_path) }
        format.xml  { render :xml => @alias, :status => :created, :location => @alias }
      else
        flash[:alert] = t('aliases.create.alert')
        format.html { render :action => "new" }
        format.xml  { render :xml => @alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aliases/1
  # PUT /aliases/1.xml
  def update
    @alias = @domain.aliases.get!(params[:id])

    respond_to do |format|
      if @alias.update(params[:alias])
        flash[:notice] = t('aliases.update.notice')
        format.html { redirect_to(aliases_path) }
        format.xml  { head :ok }
      else
        flash[:alert] = t('aliases.update.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aliases/1
  # DELETE /aliases/1.xml
  def destroy
    @alias = @domain.aliases.get!(params[:id])
    if @alias.system
      flash[:alert] = t('aliases.destroy.alert')
      return redirect_to(aliases_url)
    end
    @alias.destroy

    respond_to do |format|
      flash[:notice] = t('aliases.destroy.notice')
      format.html { redirect_to(aliases_url) }
      format.js
      format.xml  { head :ok }
    end
  end

  def set_active
    @alias = @domain.aliases.get!(params[:id])

    respond_to do |format|
      if @alias.update(:active => true)
        flash[:notice] = t('aliases.set_active.notice')
        format.html { redirect_to(aliases_path) }
        format.js { render 'active_toggle' }
        format.xml  { head :ok }
      else
        flash[:alert] = t('aliases.set_active.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  def set_inactive
    @alias = @domain.aliases.get!(params[:id])

    respond_to do |format|
      if @alias.update(:active => false)
        flash[:notice] = t('aliases.set_inactive.notice')
        format.html { redirect_to(aliases_path) }
        format.js { render 'active_toggle' }
        format.xml  { head :ok }
      else
        flash[:alert] = t('aliases.set_inactive.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  def generate
    respond_to do |format|
      if @domain.copy_default_aliases
        flash[:notice] = t('aliases.generate.notice')
        format.html { redirect_to(aliases_url) }
      else
        flash[:alert] = t('aliases.generate.alert')
        format.html { redirect_to(aliases_url) }
      end
    end
  end
end

app/views/aliases/_active_toggle.html.haml
- if a.active
  = link_to(image_tag('active.png'), set_inactive_alias_path(a), :method => :post, :remote => true)
- else 
  = link_to(image_tag('inactive.png'), set_active_alias_path(a), :method => :post, :remote => true)

app/views/aliases/_form.html.haml
= form_for(@alias) do |f|
  -if @alias.errors.any?
    #error_explanation
      %h2= "#{pluralize(@alias.errors.count, "error")} prohibited this alias address from being saved:"
      %ul
        - @alias.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend= t('.details')
    %ul
      %li
        = f.label :source
        - if !@alias.new? && @alias.source.starts_with?('@')
          = t('aliases.catchall')
        - else
          = f.text_field :source, :value => @alias.source
        %span.hint= t('.hints.source')
      %li
        = f.label :destination
        = f.text_area :destination,
          :rows => 5,
          :value => (@alias.destination ? @alias.destination_array.join("\n") : '')
        %span.hint= t('.hints.destination')
      %li
        = f.label :active
        = f.check_box :active

  %fieldset.actions
    = f.submit t('.save')
    \|
    = link_to t('.back'), aliases_path

app/views/aliases/edit.html.haml
%h1= t('.title', :name => @alias.source)

= render 'form'

app/views/aliases/index.html.haml
%h1= t('.title')
%p= t('.summary')

%table
  %thead
    %tr
      %th= t('helpers.label.alias.source')
      %th.centered= t('helpers.label.alias.active')
      %th= t('helpers.label.alias.destination')
      %th= t('helpers.label.alias.updated_at')
      - if can? :modify, Alias
        %th.right= t('.actions')

  %tbody
    - @aliases.each do |a|
      %tr{:id => "alias-#{a.id}"}
        - if a.source.starts_with? '@'
          %td= link_to t('aliases.catchall'), edit_alias_path(a)
        - else
          %td= link_to a.source, edit_alias_path(a)
        %td.centered.status
          = render :partial => 'active_toggle', :locals => {:a => a}
        %td= a.destination_array.join('<br>').html_safe
        %td
          %time{:datetime => a.updated_at, :class => 'relative'}= a.updated_at
        - if can? :manage, Alias
          %td.right
            = link_to image_tag('edit.png'), edit_alias_path(a)
            - unless a.system
              = link_to image_tag('delete.png'), a, :confirm => 'Are you sure?', :method => :delete, :remote => true