config/routes.rb
Controlr::Application.routes.draw do

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :registration => 'register',
    :sign_up => 'signup'
  }

  resources :accounts

  resources :domains do
    collection do
      post 'switch'
    end
    member do
      get 'sync'
    end
  end
  resources :users

  resources :aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :mailboxes do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :default_name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :default_aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :roles do
    collection do
      get 'report'
      post 'report'
    end
  end

  root :to => 'accounts#show'

end

app/models/domain.rb
class Domain
  include DataMapper::Resource
  extend ActiveModel::Translation

  property :id, Serial
  property :name, String, :unique => true, :required => true
  property :active, Boolean, :default => false
  property :email_active, Boolean, :default => false
  property :email_alias, String
#  property :backup_mx, Boolean, :default => 0
#  property :mailboxes_max, Integer, :default => 0, :required => false
  property :email_max_quota, Integer, :default => '200000'
  property :ftp_active, Boolean, :default => false
  property :ftp_quota, Integer, :default => 0
  property :dns_active, Boolean, :default => 0
  property :passhash, String, :length => 32
  property :created_at, DateTime
  property :updated_at, DateTime

  has n, :mailboxes, :constraint => :destroy, :order => [:email.asc]
  has n, :aliases, :constraint => :destroy, :order => [:source.asc]
  belongs_to :account
  has n, :users, :through => Resource
  has n, :name_records, :constraint => :destroy, :order => [:type.asc, :host.asc, :distance.asc]

  validates_format_of :name, :with => %r{^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,6}$}

  validates_with_block :email_active do
    if self.email_active && self.name_records.count({:type => 'MX', :active => true}) == 0
      [false, 'You need some MX records first']
    else
      true
    end
  end

  def name=(str)
    super(str.downcase) unless str.nil?
  end

  def passhash=(plain)
    super(Digest::MD5.hexdigest(plain)) unless plain.blank?
  end

  def sync_config_files
    if self.active && self.dns_active
      dns_max = self.name_records.max(:updated_at)
      generate_config(CONFIG['dns_service_type'], dns_max)
    else
      remove_config(CONFIG['dns_service_type'])
    end
  end

  def copy_default_name_records
    self.account.default_name_records.each do |dnr|
      self.name_records.first_or_create(
        {:type => dnr.type,
          :value => dnr.value,
          :host => dnr.host.blank? ? self.name : "#{dnr.host}.#{self.name}"},
          {:active => dnr.active,
            :distance => dnr.distance,
            :description => dnr.description}
      )
    end
  end

  def copy_default_aliases
    self.account.default_aliases.each do |da|
      self.aliases.first_or_create(
        {:source => "#{da.source}@#{self.name}"},
        {:destination => da.destination,
          :active => da.active,
          :system => da.system}
      )
    end
  end

  def create_gmail_name_records
    mx1 = self.name_records.first_or_create(
      {:type => 'MX',
      :host => self.name,
      :value => 'aspmx.l.google.com'},
      {:active => false,
      :distance => 1,
      :description => 'Gmail MX record'}
    )
    mx2 = self.name_records.first_or_create(
      {:type => 'MX',
      :host => self.name,
      :value => 'alt1.aspmx.l.google.com'},
      {:active => false,
      :distance => 5,
      :description => 'Gmail MX record'}
    )
    mx3 = self.name_records.first_or_create(
      {:type => 'MX',
      :host => self.name,
      :value => 'alt2.aspmx.l.google.com'},
      {:active => false,
      :distance => 5,
      :description => 'Gmail MX record'}
    )
    mx4 = self.name_records.first_or_create(
      {:type => 'MX',
      :host => self.name,
      :value => 'aspmx2.googlemail.com'},
      {:active => false,
      :distance => 10,
      :description => 'Gmail MX record'}
    )
    mx5 = self.name_records.first_or_create(
      {:type => 'MX',
      :host => self.name,
      :value => 'aspmx3.googlemail.com'},
      {:active => false,
      :distance => 10,
      :description => 'Gmail MX record'}
    )
    spf = self.name_records.first_or_create(
      {:type => 'TXT',
      :host => self.name,
      :value => 'v=spf1 include:aspmx.googlemail.com ~all'},
      {:active => false,
      :description => 'Gmail SPF record'}
    )
    return mx1 && mx2 && mx3 && mx4 && mx5 && spf
  end

  def create_gapps_name_records
    docs = self.name_records.first_or_create(
      {:type => 'CNAME',
      :host => "docs.#{self.name}",
      :value => 'ghs.google.com'},
      {:active => false,
      :description => 'Google Apps record'}
    )
    calendar = self.name_records.first_or_create(
      {:type => 'CNAME',
      :host => "calendar.#{self.name}",
      :value => 'ghs.google.com'},
      {:active => false,
      :description => 'Google Apps record'}
    )
    webmail = self.name_records.first_or_create(
      {:type => 'CNAME',
      :host => "mail.#{self.name}",
      :value => 'ghs.google.com'},
      {:active => false,
      :description => 'Google Apps record'}
    )
    return docs && calendar && webmail
  end

  private

  def generate_config(type, updated=Time.now)
    path = config_path(type)
    if !File.exists?(path) || updated >= File.stat(path).mtime
      FileUtils.mkdir_p(File.dirname(path)) if !File.exists?(path)

      template = File.open(File.join(CONFIG['template_base'],"#{type}.erb")).read

      erb = Erubis::Eruby.new(template)
      context = Erubis::Context.new()
      # use @domain in template to access domain
      context['domain'] = self
      data = erb.evaluate(context)

      File.open(path, 'w') do |file|
        file.write(data)
      end
    end
  end

  def remove_config(type)
    return nil unless type
    File.unlink(config_path(type)) if File.exists?(config_path(type))
  end

  def config_path(type)
    File.join(CONFIG['config_file_base'], type, self.name)
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  authorize_resource :except => :switch

  rescue_from DataMapper::ObjectNotFoundError do |exception|
    redirect_to(domains_path, :alert => t('domains.missing'))
  end

  # GET /domains
  # GET /domains.xml
  def index
    if can? :manage, Domain
      @domains = @account.domains.all
    else
      @domains = current_user.domains
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.xml
  def show
    @domain = @account.domains.get!(params[:id])
    session[:current_domain_id] = @domain.id if @domain

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.xml
  def new
    @domain = @account.domains.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = @account.domains.get!(params[:id])
    session[:current_domain_id] = @domain.id if @domain
  end

  # POST /domains
  # POST /domains.xml
  def create
    @domain = @account.domains.new(params[:domain])

    respond_to do |format|
      if @domain.save
        flash[:notice] = t('domains.create.notice')
        format.html { redirect_to(domain_path(@domain)) }
        format.xml  { render :xml => @domain, :status => :created, :location => @domain }
      else
        flash[:alert] = t('domains.create.alert')
        format.html { render :action => "new" }
        format.xml  { render :xml => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.xml
  def update
    @domain = @account.domains.get!(params[:id])

    respond_to do |format|
      if @domain.update(params[:domain])
        flash[:notice] = t('domains.update.notice')
        format.html { redirect_to(domain_path(@domain)) }
        format.xml  { head :ok }
      else
        flash[:alert] = t('domains.update.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.xml
  def destroy
    @domain = @account.domains.get!(params[:id])
    @domain.destroy

    respond_to do |format|
      flash[:notice] = t('domains.destroy.notice')
      format.html { redirect_to(domains_url) }
      format.xml  { head :ok }
    end
  end

  def switch
    if params[:id].empty?
      flash[:alert] = t('domains.switch.alert')
      redirect_to root_path
    else
      session[:current_domain_id] = params[:id]
      flash[:notice] = t('domains.switch.notice')
      if @domain
        redirect_back_or_default(domain_path(session[:current_domain_id]))
      else
        redirect_to(domain_path(session[:current_domain_id]))
      end
    end
  end

  def sync
    @domain = @account.domains.get!(params[:id])

    @domain.sync_config_files

    respond_to do |format|
      flash[:notice] = t('domains.sync.notice')
      format.html { redirect_to(domain_path(@domain)) }
      format.xml  { head :ok }
    end
  end

end

app/views/domains/_form.html.haml
= form_for @domain do |f|
  -if @domain.errors.any?
    .error
      %p= "#{pluralize(@domain.errors.count, "error")} stopped this domain from being saved:"
      %ul
        - @domain.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend= t('.details')
    %ul
      %li
        = f.label :name
        = f.text_field :name
        %span.hint= t('.hints.name')
      %li
        = f.label :active
        = f.check_box :active
        %span.hint= t('.hints.active')
      - if can? :manage, Account
        %li
          = f.label :account
          = collection_select(:domain, :account_id, Account.all, :id, :name)

  %fieldset
    %legend= t('.email')
    %ul
      %li
        = f.label :email_active
        = f.check_box :email_active
      %li
        = f.label :email_max_quota
        = f.text_field :email_max_quota
        %span.hint= t('.hints.email_max_quota')
      %li
        = f.label :email_alias
        %select{:name => 'domain[email_alias]'}
          %option{:value => ''}
          - @account.domains.each do |domain|
            - unless domain.new? or !can?(:read, domain) or domain == @domain or !domain.email_alias.blank?
              %option{:value => domain.name, :selected => (@domain.email_alias == domain.name) && 'selected'}= domain.name
        %span.hint= t('.hints.email_alias', :domain => @domain.name)

  %fieldset
    %legend= t('.dns')
    %ul
      %li
        = f.label :dns_active
        = f.check_box :dns_active

  %fieldset
    %legend= t('.ftp')
    %ul
      %li
        = f.label :ftp_active
        = f.check_box :ftp_active
      %li
        = f.label :passhash
        = f.password_field :passhash, :value => nil
        %span.hint= t('.hints.passhash')
      %li
        = f.label :ftp_quota
        = f.text_field :ftp_quota
        %span.hint= t('.hints.ftp_quota')

  %fieldset.actions
    = f.submit t('.save')
    \|
    = link_to t('.back'), domains_path

app/views/domains/_switch.html.haml
- if @account.domains.count > 0
  |
  = form_tag switch_domains_path, :class => 'auto-submit' do
    %select{:name => 'id'}
      %option{:value => ''}= t('.switchdomain')
      %option{:value => ''} ---
      - @account.domains.each do |domain|
        - unless domain.new? or !can?(:read, domain)
          %option{:value => domain.id, :selected => (@domain == domain) && 'selected'}= domain.name

app/views/domains/_switcher.html.haml
- if @account.domains.size > 0
  |
  = form_tag switch_domains_path, :class => 'auto-submit' do
    %select{:name => 'id'}
      %option{:value => ''}= t('.switchdomain')
      - @account.domains.each do |domain|
        - unless domain.new? or !can?(:read, domain)
          %option{:value => domain.id, :selected => (@domain == domain) && 'selected'}= domain.name

app/views/domains/edit.html.haml
%h1= t('.title', :name => @domain.name)

= render 'form'

app/views/domains/index.html.haml
%h1= t('.title')

%table
  %tr
    %th= t('helpers.label.domain.name')
    %th.centered= t('helpers.label.domain.active')
    %th.centered= t('.email_status')
    %th.centered= t('.dns_status')
    %th.centered= t('.ftp_status')
    %th= t('helpers.label.domain.updated_at')
    - if can? :manage, Domain
      %th

  - @domains.each do |domain|
    %tr
      %td= link_to domain.name, domain_path(domain)
      %td.centered= domain.active ? image_tag('active.png') : image_tag('inactive.png')
      %td.centered
        - if domain.email_active
          - if domain.email_alias.blank?
            = domain.aliases.size
            = image_tag('alias.png')
            = domain.mailboxes.size
            = image_tag('mailbox.png')
          - else
            = image_tag('redirect.png')
        - else
          = image_tag('inactive.png')
      %td.centered= domain.dns_active ? image_tag('active.png') : image_tag('inactive.png')
      %td.centered= domain.ftp_active ? image_tag('active.png') : image_tag('inactive.png')
      %td
        %time{:datetime => domain.updated_at, :class => 'relative'}= domain.updated_at
      - if can? :manage, Domain
        %td.right
          - if can? :manage, Account
            = link_to image_tag('sync.png'), sync_domain_path(domain)
          = link_to image_tag('edit.png'), edit_domain_path(domain), :title => t('actions.edit')
          = link_to image_tag('delete.png'), domain, :confirm => t('actions.confirm'), :method => :delete, :title => t('actions.delete')

app/views/domains/show.html.haml
%h1= t('.title', :name => @domain.name)

.summary
  %h2= t('.general.title')
  %table
    %tr
      %td= link_to t('.general.status'), edit_domain_path
      %td{:class => @domain.active || 'warning'}
        = @domain.active ? t('.status.active') : t('.status.inactive')
    %tr
      %td= link_to t('.general.users'), users_path
      %td
        = @domain.users.active.count
        \/
        %span.warning
          = @domain.users.inactive.count
    %tr
      %td= t('.general.created')
      %td
        %time{:datetime => @domain.created_at, :class => 'relative'}= @domain.created_at
    %tr
      %td= t('.general.updated')
      %td
        %time{:datetime => @domain.updated_at, :class => 'relative'}= @domain.updated_at
.summary
  %h2= t('.email.title')
  %table
    %tr
      %td= link_to t('.email.status'), edit_domain_path
      %td{:class => @domain.email_active || 'warning'}
        = @domain.email_active ? t('.status.active') : t('.status.inactive')
    %tr
      %td= link_to t('.email.aliases'), aliases_path
      %td
        = @domain.aliases.active.count
        \/
        %span.warning
          = @domain.aliases.inactive.count
    %tr
      %td= link_to t('.email.mailboxes'), mailboxes_path
      %td
        = @domain.mailboxes.active.count
        \/
        %span.warning
          = @domain.mailboxes.inactive.count
.summary
  %h2= t('.dns.title')
  %table
    %tr
      %td= link_to t('.dns.status'), edit_domain_path
      %td{:class => @domain.dns_active || 'warning'}
        = @domain.dns_active ? t('.status.active') : t('.status.inactive')
    %tr
      %td= link_to t('.dns.name_records'), name_records_path
      %td
        = @domain.name_records.active.count
        \/
        %span.warning
          = @domain.name_records.inactive.count
.summary
  %h2= t('.ftp.title')
  %table
    %tr
      %td= link_to t('.ftp.status'), edit_domain_path
      %td{:class => @domain.ftp_active || 'warning'}
        = @domain.ftp_active ? t('.status.active') : t('.status.inactive')