config/routes.rb
Controlr::Application.routes.draw do

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :registration => 'register',
    :sign_up => 'signup'
  }

  resources :accounts

  resources :domains do
    collection do
      post 'switch'
    end
    member do
      get 'sync'
    end
  end
  resources :users

  resources :aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :mailboxes do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :default_name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :default_aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :roles do
    collection do
      get 'report'
      post 'report'
    end
  end

  root :to => 'accounts#show'

end

app/controllers/default_aliases_controller.rb
class DefaultAliasesController < ApplicationController
  authorize_resource

  rescue_from DataMapper::ObjectNotFoundError do |exception|
    redirect_to default_aliases_path, :alert => t('default_aliases.missing')
  end

  # GET /default_aliases
  # GET /default_aliases.xml
  def index
    @default_aliases = @account.default_aliases.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @default_aliases }
    end
  end

  # GET /default_aliases/1
  # GET /default_aliases/1.xml
  def show
    redirect_to edit_default_alias_path(params[:id])
  end

  # GET /default_aliases/new
  # GET /default_aliases/new.xml
  def new
    @default_alias = @account.default_aliases.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @default_alias }
    end
  end

  # GET /default_aliases/1/edit
  def edit
    @default_alias = @account.default_aliases.get!(params[:id])
  end

  # POST /default_aliases
  # POST /default_aliases.xml
  def create
    @default_alias = @account.default_aliases.new(params[:default_alias])

    respond_to do |format|
      if @default_alias.save
        flash[:notice] = t('default_aliases.create.notice')
        format.html { redirect_to(default_aliases_path) }
        format.xml  { render :xml => @default_alias, :status => :created, :location => @default_alias }
      else
        flash[:alert] = t('default_aliases.create.alert')
        format.html { render :action => "new" }
        format.xml  { render :xml => @default_alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /default_aliases/1
  # PUT /default_aliases/1.xml
  def update
    @default_alias = @account.default_aliases.get!(params[:id])

    respond_to do |format|
      if @default_alias.update(params[:default_alias])
        flash[:notice] = t('default_aliases.update.notice')
        format.html { redirect_to(default_aliases_path) }
        format.xml  { head :ok }
      else
        flash[:alert] = t('default_aliases.update.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @default_alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /default_aliases/1
  # DELETE /default_aliases/1.xml
  def destroy
    @default_alias = @account.default_aliases.get!(params[:id])
    if @default_alias.system
      flash[:alert] = t('default_aliases.destroy.alert')
      return redirect_to(default_aliases_url)
    end
    @default_alias.destroy

    respond_to do |format|
      flash[:notice] = t('default_aliases.destroy.notice')
      format.html { redirect_to(default_aliases_url) }
      format.js
      format.xml  { head :ok }
    end
  end

  def set_active
    @default_alias = @account.default_aliases.get!(params[:id])

    respond_to do |format|
      if @default_alias.update(:active => true)
        flash[:notice] = t('default_aliases.set_active.notice')
        format.html { redirect_to(default_aliases_path) }
        format.js { render 'active_toggle' }
        format.xml  { head :ok }
      else
        flash[:alert] = t('default_aliases.set_active.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @default_alias.errors, :status => :unprocessable_entity }
      end
    end
  end

  def set_inactive
    @default_alias = @account.default_aliases.get!(params[:id])

    respond_to do |format|
      if @default_alias.update(:active => false)
        flash[:notice] = t('default_aliases.set_inactive.notice')
        format.html { redirect_to(default_aliases_path) }
        format.js { render 'active_toggle' }
        format.xml  { head :ok }
      else
        flash[:alert] = t('default_aliases.set_inactive.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @default_alias.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/views/default_aliases/_active_toggle.html.haml
- if a.active
  = link_to(image_tag('active.png'), set_inactive_default_alias_path(a), :method => :post, :remote => true)
- else 
  = link_to(image_tag('inactive.png'), set_active_default_alias_path(a), :method => :post, :remote => true)

app/views/default_aliases/_form.html.haml
= form_for(@default_alias) do |f|
  -if @default_alias.errors.any?
    #error_explanation
      %h2= "#{pluralize(@default_alias.errors.count, "error")} prohibited this alias address from being saved:"
      %ul
        - @default_alias.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend= t('.details')
    %ul
      %li
        = f.label :source
        - if !@default_alias.new? && @default_alias.source.blank?
          = t('aliases.catchall')
        - else
          = f.text_field :source, :value => @default_alias.source
        %span.hint= t('.hints.source')
      %li
        = f.label :destination
        = f.text_area :destination,
          :rows => 5,
          :value => (@default_alias.destination ? @default_alias.destination_array.join("\n") : '')
        %span.hint= t('.hints.destination')
      %li
        = f.label :active
        = f.check_box :active

  %fieldset.actions
    = f.submit t('.save')
    \|
    = link_to t('.back'), default_aliases_path

app/views/default_aliases/active_toggle.js.erb
$('#default_alias-<%= @default_alias.id %> .status').html("<%= escape_javascript( render(:partial => 'active_toggle', :locals => {:a => @default_alias}) ) %>");

app/views/default_aliases/destroy.js.erb
$('#alias-<%= @alias.id %>').remove();

app/views/default_aliases/edit.html.haml
%h1= t('.title', :name => @default_alias.source)

= render 'form'

app/views/default_aliases/index.html.haml
%h1= t('.title')
%p= t('.summary')

%table
  %thead
    %tr
      %th= t('helpers.label.alias.source')
      %th.centered= t('helpers.label.alias.active')
      %th= t('helpers.label.alias.destination')
      %th= t('helpers.label.alias.updated_at')
      - if can? :modify, Alias
        %th.right= t('.actions')

  %tbody
    - @default_aliases.each do |a|
      %tr{:id => "default_alias-#{a.id}"}
        - if a.source.blank?
          %td= link_to t('aliases.catchall'), edit_default_alias_path(a)
        - else
          %td= link_to a.source, edit_default_alias_path(a)
        %td.centered.status
          = render :partial => 'active_toggle', :locals => {:a => a}
        %td= a.destination_array.join('<br>').html_safe
        %td
          %time{:datetime => a.updated_at, :class => 'relative'}= a.updated_at
        - if can? :manage, DefaultAlias
          %td.right
            = link_to image_tag('edit.png'), edit_default_alias_path(a)
            - unless a.system
              = link_to image_tag('delete.png'), a, :confirm => t('.confirm'), :method => :delete, :remote => true

app/views/default_aliases/new.html.haml
%h1= t('.title')

= render 'form'

app/views/default_aliases/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_alias_path(@alias)
\|
= link_to 'Back', aliases_path