config/routes.rb
Controlr::Application.routes.draw do

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :registration => 'register',
    :sign_up => 'signup'
  }

  resources :accounts

  resources :domains do
    collection do
      post 'switch'
    end
    member do
      get 'sync'
    end
  end
  resources :users

  resources :aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :mailboxes do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
    collection do
      post 'generate'
    end
  end

  resources :default_name_records do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :default_aliases do
    member do
      post 'set_active'
      post 'set_inactive'
    end
  end

  resources :roles do
    collection do
      get 'report'
      post 'report'
    end
  end

  root :to => 'accounts#show'

end

app/models/account.rb
class Account
  include DataMapper::Resource
  extend ActiveModel::Translation

  property :id, Serial
  property :name, String, :required => true, :unique => true
  property :active, Boolean, :default => false
  property :created_at, DateTime
  property :updated_at, DateTime

  has n, :domains, :order => [:name.asc], :constraint => :destroy
  has n, :users, :constraint => :destroy
  has n, :default_name_records, :constraint => :destroy
  has n, :default_aliases, :constraint => :destroy

  # default default_name_records for a new account
  def create_default_name_records
    records = []
    CONFIG['nameservers'].each do |ns|
      records << self.default_name_records.first_or_create(
        {:type => 'NS',
          :value => ns},
          {:active => true,
            :description => 'Automatically generated entry'}
      )
    end
    CONFIG['mx'].each_index do |idx|
      records << self.default_name_records.first_or_create(
        {:type => 'MX',
          :value => CONFIG['mx'][idx]},
          {:active => false,
            :distance => (idx+1)*5,
            :description => 'Automatically generated entry'}
      )
    end
    # return true only if all created successfully
    return records.inject(true){|memo,r| memo && !r.nil?}
  end

  def create_default_aliases
    hostmaster = self.default_aliases.first_or_create(
      {:source => 'hostmaster'},
      {:destination => CONFIG['hostmaster'],
        :active => true,
        :system => true}
    )
    postmaster = self.default_aliases.first_or_create(
      {:source => 'postmaster'},
      {:destination => CONFIG['postmaster'],
        :active => true,
        :system => true}
    )
    abuse = self.default_aliases.first_or_create(
      {:source => 'abuse'},
      {:destination => CONFIG['abuse'],
        :active => true,
        :system => true}
    )
    catchall = self.default_aliases.first_or_create(
      {:source => ''},
      {:destination => '',
        :active => false,
        :system => true}
    )
    return hostmaster && postmaster && catchall
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  authorize_resource

  before_filter do
    session[:current_domain_id] = nil
    @domain = nil if @domain
  end

  rescue_from DataMapper::ObjectNotFoundError do |exception|
    redirect_to root_path, :alert => t('accounts.missing')
  end

  # GET /accounts
  # GET /accounts.xml
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    # this is the only action that selects the current account for super
    session[:current_account_id] = @account.id || current_user.account.id
    @account = Account.get(session[:current_account_id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.get!(params[:id])
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        flash[:notice] = t('accounts.create.notice')
        format.html { redirect_to(@account) }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        flash[:alert] = t('accounts.create.alert')
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = Account.get!(params[:id])

    respond_to do |format|
      if @account.update(params[:account])
        flash[:notice] = t('accounts.update.notice')
        format.html { redirect_to(@account) }
        format.xml  { head :ok }
      else
        flash[:alert] = t('accounts.update.alert')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = Account.get!(params[:id])
    @account.destroy

    respond_to do |format|
      flash[:notice] = t('accounts.destroy.notice')
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  -if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %ul
      %li
        = f.label :name
        = f.text_field :name, :disabled => !can?(:manage, Account)
      %li
        = f.label :active
        = f.check_box :active, :disabled => !can?(:manage, Account)

  %fieldset.actions
    = f.submit t('.save')
    \|
    = link_to t('.back'), accounts_path

app/views/accounts/edit.html.haml
%h1= t('.title', :name => @account.name)

= render 'form'

app/views/accounts/index.html.haml
%h1= t('.title')

%table
  %tr
    %th= t('attributes.name')
    %th.centered= t('attributes.active')
    %th.centered= Account.human_attribute_name('users')
    %th.centered= Account.human_attribute_name('domains')
    %th= t('attributes.created_at')
    %th= t('attributes.updated_at')
    %th

  - @accounts.each do |account|
    %tr
      %td= link_to account.name, account_path(account)
      %td.centered= account.active ? image_tag('active.png') : image_tag('inactive.png')
      %td.centered= account.users.size
      %td.centered= account.domains.size
      %td
        %time{:datetime => account.created_at, :class => 'relative'}= account.created_at
      %td
        %time{:datetime => account.updated_at, :class => 'relative'}= account.updated_at
      %td
        = link_to image_tag('edit.png'), edit_account_path(account)
        = link_to image_tag('delete.png'), account, :confirm => t('actions.confirm'), :method => :delete

app/views/accounts/show.html.haml
%h1= t('.title')
.summary